/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Test = {
  fileName?: string;
  solution?: string;
  tests: {
    testName: string;
    command: CheckIfFilesExist | TerminalCommands;
  }[];
}[];
export type Instruction = Html | Image | Hint | CommandButton;

export interface Tutorial {
  title: string;
  description: string;
  tutorialFolder: string;
  exercises?: Exercise[];
}
export interface Exercise {
  title: string;
  description: string;
  checkStartState?: Test;
  buildExercise?: TerminalCommands[];
  cleanState?: (TerminalCommands | CleanExerciseFolder)[];
  test?: Test;
  solve?: TerminalCommands[];
  content?: Instruction[];
}
export interface CheckIfFilesExist {
  checkIfFilesExist: string[];
}
export interface TerminalCommands {
  terminalCommands: string[];
}
export interface CleanExerciseFolder {
  cleanExerciseFolder: boolean;
}
export interface Html {
  html: string;
}
export interface Image {
  image: {
    src: string;
    description?: string;
    width?: "10%" | "20%" | "30%" | "40%" | "50%" | "60%" | "70%" | "80%" | "90%" | "100%";
  };
}
export interface Hint {
  hint: {
    text?: string;
    content?: (Html | Image | CommandButton)[];
  };
}
export interface CommandButton {
  button: {
    text?: string;
    commands?: (OpenFile | AutomaticImport | FileDiff | Assistance)[];
  };
}
export interface OpenFile {
  openFile: string;
  [k: string]: unknown;
}
export interface AutomaticImport {
  automaticImport: {
    imports: string[];
    path: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface FileDiff {
  fileDiff: {
    fileName: string;
    solution: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Assistance {
  assistance: {
    workspace?: string;
    elements?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
